# -*- coding: utf-8 -*-
"""
/***************************************************************************
 test1
                                 A QGIS plugin
 test1
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-20
        copyright            : (C) 2022 by priyanshu
        email                : priyanshukaushal.bt19cse@pec.edu.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load test1 class from file test1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .test1 import test1
    return test1(iface)
